# Hybrid: Complex path with straight, curves, and circular sections
# Tests geometry transitions

trajectory_generator:
  ros__parameters:
    waypoints: [
      0.0, 0.0,
      1.5, 0.0,
      2.0, 0.5,
      2.5, 1.0,
      3.0, 1.2,
      3.5, 1.0,
      4.0, 0.5,
      4.5, 0.3,
      5.0, 0.5,
      5.3, 0.8,
      5.5, 1.2,
      5.3, 1.6,
      5.0, 1.8,
      4.5, 1.6,
      4.0, 1.2,
      3.5, 0.8,
      3.0, 0.5,
      2.5, 0.4,
      2.0, 0.3,
      1.5, 0.2,
      1.0, 0.1,
      0.5, 0.0
    ]
    num_samples: 400
    desired_velocity: 0.18
    frame_id: "odom"
    use_sim_time: true

trajectory_controller:
  ros__parameters:
    lookahead_distance: 0.35
    goal_tolerance: 0.08
    use_sim_time: true

trajectory_monitor:
  ros__parameters:
    csv_output_path: "trajectory_metrics_hybrid"
    use_sim_time: true

