# S-curve trajectory configuration
# Test 3: Inflection point handling validation
# Expected: RMS error < 0.20m, completion time ~34s

trajectory_generator:
  ros__parameters:
    # S-curve: y = 0.5*sin(0.5*x), x ∈ [0, 5], 11 waypoints
    waypoints: [
      0.0, 0.0,
      0.5, 0.123936,
      1.0, 0.239713,
      1.5, 0.341213,
      2.0, 0.42074,
      2.5, 0.470625,
      3.0, 0.493691,
      3.5, 0.487754,
      4.0, 0.454649,
      4.5, 0.397815,
      5.0, 0.321874
    ]
    
    num_samples: 200
    desired_velocity: 0.15  # Slower for complex curves
    frame_id: 'odom'
    use_sim_time: true

trajectory_controller:
  ros__parameters:
    lookahead_distance: 0.30
    goal_tolerance: 0.05
    use_sim_time: true

trajectory_monitor:
  ros__parameters:
    csv_output_path: 'trajectory_metrics'
    use_sim_time: true


